### ISSUE TITLE
Allow for Nested Tables

### ISSUE THREAD

**Issue by damageboy** [zhiburt/tabled#120]
Some other terminal table "frameworks" in other languages such as, c#, C++, allow for nested tables, or in other words, the ability to render a cell with a table that is a table in itself:

Examples:

* [C# - Spectre.Console](https://spectreconsole.net) - [Example](https://spectreconsole.net/widgets/table)
* [C++ - tabulate](https://github.com/p-ranav/tabulate) - [Example](https://github.com/p-ranav/tabulate/blob/master/img/summary.png)

I think it would be useful (to me certainly:)) to have this abiltiy with tabled

**Comment by zhiburt** [comment]
Hi @damageboy 

Thank you for pointing this out.

I think `tabled` is already capable to do that?
But for sure there's no example of this .....
And some things may not be convenient? (please let me know if there's any, or open an issue).

Or do you have a specific issue?

> * [C# - Spectre.Console](https://spectreconsole.net) - [Example](https://spectreconsole.net/widgets/table)
> * [C++ - tabulate](https://github.com/p-ranav/tabulate) - [Example](https://github.com/p-ranav/tabulate/blob/master/img/summary.png)

I was not aware of these libraries thank you for links :+1: 

ref: #93 #75 #63
______

Here I tried to mimic an example you send from `Spectre.Console`.
I did not fix all borders because it would require more... code :(
And `tabled` doesn't support of colored borders yet.

```rust
use std::iter::FromIterator;

use tabled::{builder::Builder, object::Rows, Alignment, Footer, Header, Modify, Object, Style};

fn main() {
    let table1 = Builder::from_iter([
        ["CDE", "FED", "THG"],
        ["Hello\nBonjour\nHej", "World!\nle!\nVärlden!", "monde!"],
        ["EDC", "DEF", "GHI"],
    ])
    .build()
    .with(Style::extended());

    let table2 = Builder::from_iter([
        ["Foo", "Bar", "Baz"],
        ["Hello", "World!", ""],
        [&table1.to_string(), "Whaaat", "Lolz"],
        ["Hej", "Världen!", ""],
    ])
    .build()
    .with(Style::dots());

    let table3 = Builder::from_iter([
        [
            Builder::from_iter([["ABC"]]).build().to_string().as_str(),
            Builder::from_iter([["DEF"]]).build().to_string().as_str(),
            Builder::from_iter([["GHI"]]).build().to_string().as_str(),
        ],
        ["Hello", "World!", ""],
        [table2.to_string().as_str(), "Whaaat", "Lol"],
        ["Hej", "Världen!", ""],
        ["FOOTER 1", "FOOTER 2", "FOOTER 3"],
    ])
    .build();

    let table = table3
        .with(Header("TABLE TITLE"))
        .with(Footer("TABLE CAPTION"))
        .with(Modify::new(Rows::single(1).and(Rows::single(5))).with(Alignment::left()))
        .with(Modify::new(Rows::first().and(Rows::last())).with(Alignment::center()))
        .with(Style::modern());

    println!("{}", table);
}

```

![Screenshot_2022-05-05_20-13-00](https://user-images.githubusercontent.com/20165848/166976937-c8c90703-c596-4258-b1f6-3bfd9b7e5884.png)

**Comment by damageboy** [comment]
Oh thanks!

I wasn't aware this was indeed supported, I was looking for this in some of the samples and couldn't find a reference.

I'll try this next and report back!
