### ISSUE TITLE
How to compile into wasm?

### ISSUE THREAD

**Issue by songlinshu** [zhiburt/tabled#182]
HI,this is very great project.How to compile into wasm?

**Comment by zhiburt** [comment]
Hi @songlinshu 

I was actually never touched WASM previously.
But you made me try.
And it turned out a great/fun journey. 

Thank you for the question.

Here you'll find what I did to pass data from `js` to `rust`, then `rust` builds a table using `tabled`, then it `js` outputs it in HTML.

## What to do

First of all I've touched WASM literaly a few hours ago so don't blame if there's something wrong.

#### 1. Repeat what is done here https://github.com/rustwasm/wasm-bindgen/tree/main/examples/hello_world.

#### 2. Create `index.html`

```html
<html>
    <head>
      <meta content="text/html;charset=utf-8" http-equiv="Content-Type"/>
    </head>
    <body>
        <main>
        </main>
    </body>
</html>
```

#### 3. Update `webpack.config.js`

Add this to it.

```js
        new HtmlWebpackPlugin({
            template: 'index.html'
        }),
```

#### 4. Update `Cargo.toml`

```toml
[dependencies]
wasm-bindgen = "0.2.81"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tabled = { git = "https://github.com/zhiburt/tabled", branch = "master" }
```

#### 5. Update `lib.rs`

```rust
use serde::Deserialize;
use tabled::{Tabled, Style};
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub fn build_issues(json: &str) -> String {
    let issues: Vec<Issue> = match serde_json::from_str(json) {
        Ok(v) => v,
        Err(err) => return format!("ERROR: {}", err),
    };
    tabled::Table::new(issues).with(Style::modern()).to_string()
}

#[derive(Debug, Tabled, Deserialize)]
struct Issue {
    author: String,
    message: String,
    #[tabled(display_with = "display_labels")]
    labels: Vec<String>,
}

fn display_labels(labels: &Vec<String>) -> String {
    format!("{:?}", labels)
}
```

#### 6. Update `index.js` 

```js
const rust = import('./pkg');

rust
  .then(m => {
    const issues = [
      { "author": "songlinshu", "message": "How to use it in WASM", "labels": ["question", "interesting"] },
      { "author": "zhiburt", "message": "thank you for the question", "labels": [] },
    ];
    const json = JSON.stringify(issues)
    const table = m.build_issues(json)
    const tableDiv = document.createElement('div');
    tableDiv.innerHTML = `<tt style='white-space: pre;background-color: pink;'>`+ table + `</tt>`;
    // ✅ Insert element as first in body
    document.body.insertAdjacentElement('afterbegin', tableDiv);
  })
  .catch(console.error);
```

#### Run it.

```bash
npm run serve
```

Voila

![image](https://user-images.githubusercontent.com/20165848/178155505-73f1a12f-e38c-403e-935e-4279b14453d1.png)

## Notes:

I've used tt block in order to have a monospace rendering.
I guess not all browsers support it.
And it maybe not be convenient in some situations 

## References:
- https://rustwasm.github.io/docs/wasm-bindgen/examples/hello-world.html
- https://www.w3schools.com/tags/tag_tt.asp
- https://www.webassemblyman.com/rust_webassembly_hello_world.html

**Comment by zhiburt** [comment]
I guess it could be worth to create a simple example for it.
Don't you want to try it?

It will be necessary to create such sample project under `examples/` directory (like in `examples/wasm_example`) and create a `README.md` for it.

**Comment by zhiburt** [comment]
I am curious though,
Is this what you @songlinshu have expected?
Or you were thinking that there's some special support for WASM? (like output html instead of text)

**Comment by songlinshu** [comment]
Thank you !

**Comment by zhiburt** [comment]
I'll close it then if you don't mind.

Take care. Have a great one.
